# Generated by Django 4.1 on 2026-05-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_conge_id_alter_employe_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='Service',
            new_name='service',
        ),
    ]
